#!/bin/bash
# Railway Deployment Guide for Online Notes App

echo "🚀 Railway Deployment Guide"
echo "=========================="
echo ""

echo "📋 Prerequisites:"
echo "1. GitHub account with your repository pushed"
echo "2. Railway.app account (free tier available)"
echo ""

echo "🔧 Step 1: Deploy Backend"
echo "-------------------------"
echo "1. Go to https://railway.app"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Select your 'Notes_Repository'"
echo "5. Choose 'backend' folder as root directory"
echo "6. Railway will auto-detect Python and deploy"
echo ""

echo "⚙️  Step 2: Configure Backend Environment Variables"
echo "---------------------------------------------------"
echo "In Railway dashboard → your backend service → Variables tab:"
echo "Add these variables:"
echo "- SECRET_KEY = your-secret-key-here"
echo "- DATABASE_URL = (Railway will provide PostgreSQL automatically)"
echo ""

echo "🌐 Step 3: Deploy Frontend"
echo "--------------------------"
echo "1. In the same Railway project, click 'New Service'"
echo "2. Select 'Deploy from GitHub repo' again"
echo "3. Choose your repository again"
echo "4. This time select 'frontend' folder as root directory"
echo "5. Railway will auto-detect React and deploy"
echo ""

echo "🔗 Step 4: Connect Frontend to Backend"
echo "--------------------------------------"
echo "1. Copy your backend Railway URL (ends with .railway.app)"
echo "2. In Railway dashboard → frontend service → Variables tab:"
echo "3. Add: REACT_APP_API_URL = https://your-backend-url.railway.app"
echo ""

echo "🗄️  Step 5: Setup Database"
echo "-------------------------"
echo "1. In Railway dashboard → Add PostgreSQL database"
echo "2. Railway will automatically connect it to your backend"
echo "3. Your app will create tables automatically on first run"
echo ""

echo "✅ Step 6: Final Configuration"
echo "------------------------------"
echo "1. Update CORS in backend to include your frontend Railway URL"
echo "2. Test your deployed application"
echo "3. Your app will be live at both URLs!"
echo ""

echo "🎉 Deployment Complete!"
echo "Your app will be available at:"
echo "Frontend: https://your-frontend.railway.app"
echo "Backend API: https://your-backend.railway.app"
echo ""

echo "📝 Notes:"
echo "- Free tier includes 500 hours/month"
echo "- Automatic HTTPS and custom domains available"
echo "- Auto-deploys on git push"
echo "- Built-in monitoring and logs"